import type { LanguageCode, VoiceExchange } from '../types';
import { getCurrentSession } from './authService';

export interface AIMessage { role:'user'|'assistant'; content:string; }
export class AIServiceError extends Error { code:'not-configured'|'request-failed'|'invalid-response'; constructor(message:string,code:'not-configured'|'request-failed'|'invalid-response'){super(message);this.name='AIServiceError';this.code=code;} }
const ENDPOINT='/api/voice/chat';

async function loadDatabaseContext(){const session=getCurrentSession();if(!session?.profile?.id||session.role==='admin')return '';try{const response=await fetch(`/api/kisanlink/voice-context?role=${session.role}&userId=${encodeURIComponent(session.profile.id)}`);return response.ok?JSON.stringify(await response.json()):'';}catch{return '';}}
async function loadWebContext(question:string){if(!question.trim())return '';try{const response=await fetch(`/api/web/search?q=${encodeURIComponent(question)}`);if(!response.ok)return '';const payload=await response.json() as {items?:Array<{title?:string;snippet?:string;link?:string;source?:string}>;source?:string};if(!Array.isArray(payload.items)||!payload.items.length)return '';return JSON.stringify({source:payload.source||'web',results:payload.items.slice(0,5)});}catch{return '';}}

function localDatabaseAnswer(question:string,raw:string,language:LanguageCode,webRaw=''):string{
  try{
    const data=JSON.parse(raw) as any;const q=question.toLowerCase();const farmer=data.farmer;const buyer=data.buyer;const listings=Array.isArray(data.listings)?data.listings:[];const buyers=Array.isArray(data.buyers)?data.buyers:[];const requests=Array.isArray(data.requests)?data.requests:[];const crop=farmer?.id?(listings[0]?.crop_name||listings[0]?.cropName||''):'';const qty=farmer?.id?(listings[0]?.quantity_quintals||listings[0]?.quantityQuintals||0):0;const buyerCrops=buyer?.crops_json?JSON.parse(buyer.crops_json):(buyer?.crops||[]);
    const cropWords=['crop','produce','selling','sell','what am i selling','పంట','फसल','पीक'];const buyerWords=['buyer','buyers','who can buy','खरीदार','खरेदीदार','కొనుగోలు','కొనేవారు'];const requestWords=['request','requests','connect','connection','अभ्यर्थन','अनुरोध','विनंती','కనెక్షన్','అభ్యర్థన'];const farmerWords=['farmer','farmers','రైతు','किसान','शेतकरी'];const demandWords=['want','need','demand','wanted','కావాలి','चाहिए','हवे'];const has=(words:string[])=>words.some(word=>q.includes(word));
    if(has(cropWords)){if(crop)return `Your saved crop is ${crop}${qty?` with ${qty} quintals`:''}. This is from your live KisanLink database.`;return 'No crop has been saved yet. Add your crop details on the home page first.';}
    if(has(demandWords)&&buyer)return `Your current buyer demand is ${buyerCrops.join(', ')||'not set'}, with a typical quantity of ${buyer.typical_quantity||0} quintals. You can update it in My demand.`;
    if(has(buyerWords)&&farmer){if(!buyers.length)return 'There are no registered buyers in the database.';return `I found ${buyers.length} registered buyers: ${buyers.slice(0,4).map((b:any)=>b.name).join(', ')}. The buyer records come from the live database.`;}
    if(has(farmerWords)&&buyer){const wanted=buyerCrops.map((value:string)=>value.toLowerCase());const matches=listings.filter((listing:any)=>wanted.some((word:string)=>String(listing.crop_name||listing.cropName).toLowerCase().includes(word)));if(!matches.length)return 'No current farmer listing matches your buyer demand.';return `I found ${matches.length} farmer listings matching your demand. The latest is ${matches[0].crop_name||matches[0].cropName} from ${matches[0].farmer_name||matches[0].farmerName}, ${matches[0].quantity_quintals||matches[0].quantityQuintals} quintals.`;}
    if(has(requestWords)){if(!requests.length)return 'You have no connection requests yet.';return requests.slice(0,5).map((request:any)=>`${request.buyerName||request.farmerName}: ${request.status} for ${request.cropName}, ${request.requestedQuantity} quintals.`).join(' ');}
    if(q.includes('contact')||q.includes('phone')||q.includes('mobile')||q.includes('email')||q.includes('नंबर')||q.includes('ఫోన్')){const accepted=requests.filter((request:any)=>request.status==='accepted');if(!accepted.length)return 'No accepted connection is available, so protected contact details cannot be shared yet.';return accepted.map((request:any)=>request.buyerName?`${request.buyerName}: ${request.buyerMobile||'mobile unavailable'}${request.buyerEmail?`, ${request.buyerEmail}`:''}`:`${request.farmerName}: ${request.farmerMobile||'mobile unavailable'}${request.farmerEmail?`, ${request.farmerEmail}`:''}`).join(' ');}
    if(webRaw){try{const web=JSON.parse(webRaw) as any;if(Array.isArray(web.results)&&web.results.length){const top=web.results[0];return `I found current web information for your question. ${top.title||''}. ${top.snippet||''} Source: ${top.source||'Google'}. For exact local prices, verify the latest mandi record before selling.`;}}catch{}}
    if(language==='hi')return 'मैंने आपका लाइव KisanLink डेटाबेस और उपलब्ध वेब जानकारी देखी है। अपनी फसल, खरीदार, मांग, कीमत या कनेक्शन के बारे में पूछें।';
    if(language==='te')return 'నేను మీ లైవ్ KisanLink డేటాబేస్ మరియు అందుబాటులో ఉన్న వెబ్ సమాచారాన్ని చూశాను. పంట, కొనుగోలుదారు, డిమాండ్, ధర లేదా కనెక్షన్ గురించి అడగండి.';
    if(language==='mr')return 'मी तुमचा लाइव्ह KisanLink डेटाबेस आणि उपलब्ध वेब माहिती तपासली आहे. पिकाबद्दल, खरेदीदारांबद्दल, मागणी, किंमत किंवा कनेक्शनबद्दल विचारा.';
    return 'I checked your live KisanLink database and available current web information. Ask me about your crop, buyers, demand, prices, farmer listings, or connection requests.';
  }catch{return 'I could not read the current KisanLink data. Please try again.';}
}

export async function askAgriculturalAI(messages:AIMessage[],language:LanguageCode):Promise<string>{
  const context=messages.slice(-12);const userMessages=context.filter(message=>message.role==='user');const last=userMessages.length?userMessages[userMessages.length-1].content:'';const database=await loadDatabaseContext();const web=await loadWebContext(last);
  const trustedContext=[database?`KISANLINK DATABASE CONTEXT — trusted live application data. Use it as the source of truth for the user's account. Never invent live records. Only reveal another party's mobile/email when a request is accepted.\n${database}`:'',web?`CURRENT WEB CONTEXT — retrieved for this question because it may need current information. Treat it as supporting external context, not as account truth. Cite the source name in plain language when useful. Never invent exact prices from snippets.\n${web}`:''].filter(Boolean).join('\n\n');
  const contextMessage:AIMessage|null=trustedContext?{role:'user',content:trustedContext}:null;const aiMessages:AIMessage[]=contextMessage?[contextMessage,...context]:context;
  try{const response=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({language,messages:aiMessages,systemPrompt:'You are KisanLink KisanVoice. Understand Indian languages, dialects, transliteration, accents and mixed-language farmer speech. Answer dynamically from the latest user question. Use live KisanLink database context for account facts and current web context when supplied for timely external information. Never invent application records, contacts, or exact live prices. If web information is only a snippet, say so and recommend verifying the latest local mandi/source when money decisions depend on it.'})});
    if(!response.ok){if(database)return localDatabaseAnswer(last,database,language,web);throw new AIServiceError('KisanVoice AI is unavailable.','request-failed');}
    const payload=await response.json() as any;const content=typeof payload.response==='string'?payload.response:typeof payload.message?.content==='string'?payload.message.content:Array.isArray(payload.choices)?(payload.choices[0]?.message?.content||payload.choices[0]?.text):undefined;
    if(typeof content!=='string'||!content.trim())return database?localDatabaseAnswer(last,database,language,web):'I could not generate an answer. Please try again.';return content.trim();
  }catch(error){if(database)return localDatabaseAnswer(last,database,language,web);if(error instanceof AIServiceError)throw error;throw new AIServiceError('KisanVoice is temporarily unavailable.','request-failed');}
}
export function exchangesToMessages(exchanges:VoiceExchange[]):AIMessage[]{return exchanges.slice(-12).map(exchange=>({role:exchange.role,content:exchange.text}));}
