import type { LanguageCode, VoiceExchange } from '../types';
import { getCurrentSession } from './authService';

export interface AIMessage { role: 'user' | 'assistant'; content: string; }
export class AIServiceError extends Error { code: 'not-configured' | 'request-failed' | 'invalid-response'; constructor(message:string,code:'not-configured'|'request-failed'|'invalid-response'){super(message);this.name='AIServiceError';this.code=code;} }
const DEFAULT_AI_ENDPOINT='/api/voice/chat';
function getAIEndpoint(){return import.meta.env.VITE_AI_API_URL?.trim()||DEFAULT_AI_ENDPOINT;}
async function loadDatabaseContext(){const session=getCurrentSession();if(!session?.profile?.id||session.role==='admin')return '';try{const response=await fetch(`/api/kisanlink/voice-context?role=${session.role}&userId=${encodeURIComponent(session.profile.id)}`);if(!response.ok)return '';return JSON.stringify(await response.json());}catch{return '';}}
export async function askAgriculturalAI(messages:AIMessage[],language:LanguageCode):Promise<string>{const endpoint=getAIEndpoint();const context=messages.slice(-12);const databaseContext=await loadDatabaseContext();let response:Response;try{response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({language,messages:context,databaseContext,systemPrompt:'You are KisanLink’s in-app farmer decision assistant. Understand multilingual and mixed-language farmer speech. Reply in the selected application language. DATABASE_CONTEXT contains current SQLite data for the logged-in user and is the source of truth for their profile, produce, buyers, marketplace listings, and connection requests. Use it to answer questions about their crop, quantity, buyers, requests, accepted connections, and marketplace. Do not invent records. Reveal the other party mobile/email only when the related connection request is accepted; never reveal protected contact details for pending or rejected requests. If no matching database record exists, say so clearly. For selling, quality, or price questions, use these plain-text sections in order: PRODUCT AND REQUEST, QUALITY CHECK, PRICE ANALYSIS, BEST RECOMMENDATION, OTHER OPTIONS, NEXT STEPS. Use short bullet lines, no Markdown tables, pipes, long paragraphs, or raw symbols such as ###, **, or ---. Repeat product and quantity when known. Without submitted crop images or structured assessment, quality guidance is preliminary. Never invent live prices.'})});}catch{throw new AIServiceError('AI assistant is currently unavailable. Please check the AI configuration.','request-failed');}if(!response.ok){const e=await response.json().catch(()=>null) as any;if(response.status===503||typeof e?.error==='string'&&e.error.toLowerCase().includes('not configured'))throw new AIServiceError('AI assistant is currently unavailable. Please check the AI configuration.','not-configured');throw new AIServiceError('AI assistant is currently unavailable. Please check the AI configuration.','request-failed');}let payload:unknown;try{payload=await response.json();}catch{throw new AIServiceError('AI assistant is currently unavailable. Please check the AI configuration.','invalid-response');}const content=typeof(payload as any)?.response==='string'?(payload as any).response:typeof(payload as any)?.message?.content==='string'?(payload as any).message.content:Array.isArray((payload as any)?.choices)?(payload as any).choices[0]?.message?.content||(payload as any).choices[0]?.text:undefined;if(typeof content!=='string'||!content.trim())throw new AIServiceError('AI assistant is currently unavailable. Please check the AI configuration.','invalid-response');return content.trim();}
export function exchangesToMessages(exchanges:VoiceExchange[]):AIMessage[]{return exchanges.slice(-12).map(exchange=>({role:exchange.role,content:exchange.text}));}
