import type { AccountRole, AppProfile, AuthSession, BuyerProfile, FarmerProfile, FarmerProduce, LanguageCode } from '../types';
import { syncFarmer, syncBuyer } from './marketService';
const ACCOUNTS_KEY='kisanlink-accounts'; const CURRENT_USER_KEY='kisanlink-current-user';
interface StoredAccount { role:AccountRole; profile:AppProfile; passwordHash:string; aadhaarHash?:string; mobileKey:string; emailKey?:string; }
export interface RegistrationInput { name:string; mobile:string; email?:string; aadhaar:string; password:string; language:LanguageCode; district:string; }
export interface BuyerRegistrationInput { businessName:string; mobile:string; email?:string; aadhaar:string; password:string; language:LanguageCode; state:string; district:string; buyerType:BuyerProfile['buyerType']; crops:string[]; preferredGrades:BuyerProfile['preferredGrades']; typicalQuantityQuintals:number; }
export interface AuthResult { ok:boolean; error?:string; profile?:AppProfile; role?:AccountRole; }
function readAccounts():StoredAccount[]{if(typeof window==='undefined')return[];try{const v=JSON.parse(window.localStorage.getItem(ACCOUNTS_KEY)||'[]');return Array.isArray(v)?v.map(a=>({...a,role:a.role||(((a.profile as BuyerProfile).role==='buyer')?'buyer':'farmer')})) as StoredAccount[]:[];}catch{return[];}}
function normalize(v:string){return v.trim().toLowerCase();} function normalizeIdentifier(v:string){const t=v.trim();return t.includes('@')?normalize(t):t.replace(/\D/g,'');}
async function hashValue(v:string){if(typeof crypto!=='undefined'&&crypto.subtle){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,'0')).join('');}return normalize(v);}
function saveAccounts(a:StoredAccount[]){window.localStorage.setItem(ACCOUNTS_KEY,JSON.stringify(a));} function saveCurrentProfile(p:FarmerProfile){window.localStorage.setItem(CURRENT_USER_KEY,JSON.stringify({role:'farmer',profile:p}));} function saveCurrentSession(s:AuthSession){window.localStorage.setItem(CURRENT_USER_KEY,JSON.stringify(s));}
export function getCurrentSession():AuthSession|null{if(typeof window==='undefined')return null;try{const v=JSON.parse(window.localStorage.getItem(CURRENT_USER_KEY)||'null');if(v?.profile&&v?.role)return v as AuthSession;if(v?.id)return{role:'farmer',profile:v as FarmerProfile};return null;}catch{return null;}}
export function getCurrentProfile(){const s=getCurrentSession();return s?.role==='farmer'?s.profile as FarmerProfile:null;} export function clearCurrentProfile(){if(typeof window!=='undefined')window.localStorage.removeItem(CURRENT_USER_KEY);}
export async function registerAccount(input:RegistrationInput):Promise<AuthResult>{const aadhaar=input.aadhaar.replace(/\D/g,'');const mobileKey=normalizeIdentifier(input.mobile);const emailKey=input.email?.trim()?normalize(input.email):undefined;const accounts=readAccounts();const aadhaarHash=await hashValue(aadhaar);if(accounts.some(a=>a.aadhaarHash===aadhaarHash))return{ok:false,error:'This Aadhaar number is already associated with an account.'};if(accounts.some(a=>a.mobileKey===mobileKey||(emailKey&&a.emailKey===emailKey)))return{ok:false,error:'An account already exists with this mobile number or email.'};const profile:FarmerProfile={id:`farmer-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,name:input.name.trim(),mobile:input.mobile.trim(),email:input.email?.trim()||undefined,aadhaarLast4:aadhaar.slice(-4),district:input.district.trim(),language:input.language,createdAt:new Date().toISOString()};accounts.push({role:'farmer',profile,passwordHash:await hashValue(input.password),aadhaarHash,mobileKey,emailKey});saveAccounts(accounts);saveCurrentProfile(profile);void syncFarmer(profile);return{ok:true,profile,role:'farmer'};}
export async function loginAccount(i:string,p:string){return loginForRole(i,p,'farmer');}
export async function registerBuyerAccount(input:BuyerRegistrationInput):Promise<AuthResult>{const aadhaar=input.aadhaar.replace(/\D/g,'');const mobileKey=normalizeIdentifier(input.mobile);const emailKey=input.email?.trim()?normalize(input.email):undefined;const accounts=readAccounts();const aadhaarHash=await hashValue(aadhaar);if(accounts.some(a=>a.aadhaarHash===aadhaarHash))return{ok:false,error:'This Aadhaar number is already associated with an account.'};if(accounts.some(a=>a.mobileKey===mobileKey||(emailKey&&a.emailKey===emailKey)))return{ok:false,error:'An account already exists with this mobile number or email.'};const profile:BuyerProfile={id:`buyer-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,role:'buyer',businessName:input.businessName.trim(),mobile:input.mobile.trim(),email:input.email?.trim()||undefined,state:input.state.trim(),district:input.district.trim(),buyerType:input.buyerType,crops:input.crops.map(c=>c.trim()).filter(Boolean),preferredGrades:input.preferredGrades,typicalQuantityQuintals:input.typicalQuantityQuintals,language:input.language,createdAt:new Date().toISOString(),verified:false,trust:{trustScore:72,completedDeals:0,successfulDeals:0,onTimePaymentPct:0,complaints:0}};accounts.push({role:'buyer',profile,passwordHash:await hashValue(input.password),aadhaarHash,mobileKey,emailKey});saveAccounts(accounts);saveCurrentSession({role:'buyer',profile});void syncBuyer(profile);return{ok:true,profile,role:'buyer'};}
export async function loginBuyerAccount(i:string,p:string){return loginForRole(i,p,'buyer');}
async function loginForRole(identifier:string,password:string,role:AccountRole):Promise<AuthResult>{const key=normalizeIdentifier(identifier);const passwordHash=await hashValue(password);const accounts=readAccounts();let account=accounts.find(a=>a.role===role&&(a.mobileKey===key||a.emailKey===key));if(!account&&/^\d{12}$/.test(key)){const aadhaarHash=await hashValue(key);account=accounts.find(a=>a.role===role&&a.aadhaarHash===aadhaarHash);}if(!account||account.passwordHash!==passwordHash)return{ok:false,error:'The login details do not match an account.'};saveCurrentSession({role:account.role,profile:account.profile});if(account.role==='farmer')void syncFarmer(account.profile as FarmerProfile);else void syncBuyer(account.profile as BuyerProfile);return{ok:true,profile:account.profile,role:account.role};}
export function updateStoredLanguage(profile:AppProfile,language:LanguageCode){const updatedProfile={...profile,language};saveAccounts(readAccounts().map(a=>a.profile.id===profile.id?{...a,profile:updatedProfile}:a));saveCurrentSession({role:'role'in profile?'buyer':'farmer',profile:updatedProfile});if('role'in updatedProfile)void syncBuyer(updatedProfile as BuyerProfile);else void syncFarmer(updatedProfile as FarmerProfile);return updatedProfile;}
export function updateStoredProduce(profile:FarmerProfile,produce:FarmerProduce){const updatedProfile={...profile,produce};saveAccounts(readAccounts().map(a=>a.profile.id===profile.id?{...a,profile:updatedProfile}:a));saveCurrentProfile(updatedProfile);void syncFarmer(updatedProfile);return updatedProfile;}
export function getFarmerProfiles():FarmerProfile[]{return readAccounts().filter(a=>a.role==='farmer').map(a=>a.profile as FarmerProfile);}
