import type { LanguageCode } from '../types';
export interface SpeechTranscription{text:string;language?:LanguageCode;}
export class SpeechServiceError extends Error{code:'not-configured'|'permission-denied'|'recording-failed'|'transcription-failed';constructor(message:string,code:'not-configured'|'permission-denied'|'recording-failed'|'transcription-failed'){super(message);this.name='SpeechServiceError';this.code=code;}}
const DEFAULT_STT_ENDPOINT='/api/voice/transcribe';
function getSTTEndpoint(){return import.meta.env.VITE_STT_API_URL?.trim()||DEFAULT_STT_ENDPOINT;}
function browserRecognition(){if(typeof window==='undefined')return null;const w=window as any;return w.SpeechRecognition||w.webkitSpeechRecognition||null;}
export function isSpeechServiceConfigured(){return true;}
async function transcribeAudio(audio:Blob,languageHint:'auto'|LanguageCode='auto'):Promise<SpeechTranscription>{const form=new FormData();form.append('audio',audio,'kisanvoice.webm');form.append('language',languageHint);try{const r=await fetch(getSTTEndpoint(),{method:'POST',body:form});if(r.ok){const p=await r.json() as any;const text=typeof p.text==='string'?p.text:p.transcript;if(typeof text==='string'&&text.trim())return{text:text.trim(),language:typeof(p.language||p.lang)==='string'?(p.language||p.lang):undefined};}}catch{}throw new SpeechServiceError('I couldn’t understand the audio. Please try again.','transcription-failed');}
const LANG_MAP:Record<string,string>={en:'en-IN',hi:'hi-IN',mr:'mr-IN',te:'te-IN',ta:'ta-IN',kn:'kn-IN',bn:'bn-IN',gu:'gu-IN',pa:'pa-IN',ur:'ur-IN',ml:'ml-IN',as:'as-IN',or:'or-IN'};
export class SpeechRecorder{private recorder:MediaRecorder|null=null;private stream:MediaStream|null=null;private chunks:Blob[]=[];private stopPromise:Promise<SpeechTranscription>|null=null;private recognition:any=null;private usingBrowserRecognition=false;private completed=false;
 async start(languageHint:LanguageCode='en',onComplete?:(result:SpeechTranscription)=>void){const Recognition=browserRecognition();if(Recognition){try{this.usingBrowserRecognition=true;this.completed=false;this.recognition=new Recognition();this.recognition.continuous=false;this.recognition.interimResults=true;this.recognition.lang=LANG_MAP[languageHint]||'en-IN';this.stopPromise=new Promise((resolve,reject)=>{this.recognition.onresult=(event:any)=>{let text='';for(let i=0;i<event.results.length;i++)text+=(event.results[i][0]?.transcript||'')+' ';this.finish({text:text.trim(),language:languageHint},resolve,onComplete);};this.recognition.onerror=(event:any)=>{if(event?.error==='not-allowed'||event?.error==='service-not-allowed')reject(new SpeechServiceError('Microphone permission is required for voice questions.','permission-denied'));else if(event?.error==='no-speech')reject(new SpeechServiceError('No speech was detected. Tap the microphone and speak clearly.','transcription-failed'));else reject(new SpeechServiceError('I couldn’t understand the audio. Please try again.','recording-failed'));};this.recognition.onend=()=>{if(!this.completed)reject(new SpeechServiceError('No speech was detected. Tap the microphone and speak clearly.','transcription-failed'));};});this.recognition.start();return;}catch(e){this.recognition=null;this.usingBrowserRecognition=false;if(e instanceof SpeechServiceError)throw e;}}
 if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined')throw new SpeechServiceError('Voice input is unavailable. Please use the typing option.','recording-failed');try{this.stream=await navigator.mediaDevices.getUserMedia({audio:true});const mime=['audio/webm;codecs=opus','audio/webm','audio/mp4'].find(x=>MediaRecorder.isTypeSupported(x))||'';this.recorder=new MediaRecorder(this.stream,mime?{mimeType:mime}:undefined);this.chunks=[];this.completed=false;this.stopPromise=new Promise((resolve,reject)=>{this.recorder!.ondataavailable=e=>{if(e.data.size)this.chunks.push(e.data);};this.recorder!.onerror=()=>reject(new SpeechServiceError('Recording failed. Please try again.','recording-failed'));this.recorder!.onstop=async()=>{this.stream?.getTracks().forEach(t=>t.stop());this.stream=null;try{const result=await transcribeAudio(new Blob(this.chunks,{type:this.recorder?.mimeType||'audio/webm'}),'auto');this.finish(result,resolve,onComplete);}catch(e){reject(e);}};});this.recorder.start();}catch(e){this.stream?.getTracks().forEach(t=>t.stop());this.stream=null;throw e instanceof SpeechServiceError?e:new SpeechServiceError('Microphone permission is required for voice questions.','recording-failed');}}
 private finish(result:SpeechTranscription,resolve:(r:SpeechTranscription)=>void,onComplete?:((r:SpeechTranscription)=>void)){if(this.completed)return;this.completed=true;resolve(result);try{onComplete?.(result);}catch{}}
 waitForResult(){if(!this.stopPromise)return Promise.reject(new SpeechServiceError('Voice recording has not started.','recording-failed'));return this.stopPromise;}
 stop(languageHint:'auto'|LanguageCode='auto'){if(this.usingBrowserRecognition&&this.recognition&&this.stopPromise){try{this.recognition.stop();}catch{}return this.stopPromise.then(r=>{if(languageHint!=='auto')r.language=languageHint;return r;});}if(!this.recorder||this.recorder.state==='inactive'||!this.stopPromise)return Promise.reject(new SpeechServiceError('Voice recording has not started.','recording-failed'));this.recorder.stop();return this.stopPromise.then(r=>{if(languageHint!=='auto')r.language=languageHint;return r;});}
 cancel(){try{this.recognition?.abort();}catch{}this.recognition=null;this.usingBrowserRecognition=false;if(this.recorder&&this.recorder.state!=='inactive')this.recorder.stop();this.stream?.getTracks().forEach(t=>t.stop());this.stream=null;this.recorder=null;this.stopPromise=null;this.completed=true;}}
