import type { LanguageCode } from '../types';
export interface SpeechTranscription{text:string;language?:LanguageCode;}
export class SpeechServiceError extends Error{code:'not-configured'|'permission-denied'|'recording-failed'|'transcription-failed';constructor(message:string,code:'not-configured'|'permission-denied'|'recording-failed'|'transcription-failed'){super(message);this.name='SpeechServiceError';this.code=code;}}
const LANG_MAP:Record<string,string>={en:'en-IN',hi:'hi-IN',mr:'mr-IN',te:'te-IN',ta:'ta-IN',kn:'kn-IN',bn:'bn-IN',gu:'gu-IN',pa:'pa-IN',ur:'ur-IN',ml:'ml-IN',as:'as-IN',or:'or-IN'};
const ENDPOINT='/api/voice/transcribe';
function RecognitionCtor(){if(typeof window==='undefined')return null;const w=window as any;return w.SpeechRecognition||w.webkitSpeechRecognition||null;}
async function transcribeAudio(audio:Blob,language:'auto'|LanguageCode){const form=new FormData();form.append('audio',audio,'kisanvoice.webm');form.append('language',language);try{const r=await fetch(ENDPOINT,{method:'POST',body:form});if(r.ok){const p=await r.json() as any;const text=typeof p.text==='string'?p.text:p.transcript;if(text?.trim())return{text:text.trim(),language:typeof p.language==='string'?p.language:undefined};}}catch{}throw new SpeechServiceError('I couldn’t understand the audio. Please try again.','transcription-failed');}
export class SpeechRecorder{private recognition:any=null;private recorder:MediaRecorder|null=null;private stream:MediaStream|null=null;private chunks:Blob[]=[];private promise:Promise<SpeechTranscription>|null=null;private done=false;
 async start(language:LanguageCode='en',onComplete?:(r:SpeechTranscription)=>void){const Ctor=RecognitionCtor();if(Ctor){try{this.done=false;this.recognition=new Ctor();this.promise=new Promise((resolve,reject)=>{this.recognition.lang=LANG_MAP[language]||'en-IN';this.recognition.continuous=false;this.recognition.interimResults=false;this.recognition.maxAlternatives=1;this.recognition.onresult=(event:any)=>{const text=String(event.results?.[0]?.[0]?.transcript||'').trim();if(!text){reject(new SpeechServiceError('I could not hear a clear question. Please try again.','transcription-failed'));return;}this.finish({text,language},resolve,onComplete);};this.recognition.onerror=(event:any)=>{if(this.done)return;const code=event?.error;if(code==='not-allowed'||code==='service-not-allowed')reject(new SpeechServiceError('Please allow microphone access for KisanVoice.','permission-denied'));else if(code==='no-speech')reject(new SpeechServiceError('No speech was detected. Speak for a few seconds after tapping the microphone.','transcription-failed'));else reject(new SpeechServiceError('Voice recognition failed. Please try again.','recording-failed'));};this.recognition.onend=()=>{if(!this.done)reject(new SpeechServiceError('No speech was detected. Speak clearly and try again.','transcription-failed'));};});this.recognition.start();return;}catch(e){this.recognition=null;if(e instanceof SpeechServiceError)throw e;}}
 if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined')throw new SpeechServiceError('Voice input is unavailable in this browser. Use the typing option.','recording-failed');try{this.stream=await navigator.mediaDevices.getUserMedia({audio:true});const mime=['audio/webm;codecs=opus','audio/webm','audio/mp4'].find(x=>MediaRecorder.isTypeSupported(x))||'';this.recorder=new MediaRecorder(this.stream,mime?{mimeType:mime}:undefined);this.chunks=[];this.done=false;this.promise=new Promise((resolve,reject)=>{this.recorder!.ondataavailable=e=>{if(e.data.size)this.chunks.push(e.data);};this.recorder!.onerror=()=>reject(new SpeechServiceError('Recording failed. Please try again.','recording-failed'));this.recorder!.onstop=async()=>{this.stream?.getTracks().forEach(t=>t.stop());this.stream=null;try{const r=await transcribeAudio(new Blob(this.chunks,{type:this.recorder?.mimeType||'audio/webm'}),'auto');this.finish(r,resolve,onComplete);}catch(e){reject(e);}};});this.recorder.start();}catch(e){this.stream?.getTracks().forEach(t=>t.stop());this.stream=null;throw e instanceof SpeechServiceError?e:new SpeechServiceError('Please allow microphone access for KisanVoice.','permission-denied');}}
 private finish(r:SpeechTranscription,resolve:(r:SpeechTranscription)=>void,onComplete?:((r:SpeechTranscription)=>void)){if(this.done)return;this.done=true;resolve(r);onComplete?.(r);}
 waitForResult(){return this.promise||Promise.reject(new SpeechServiceError('Voice recording has not started.','recording-failed'));}
 stop(language:'auto'|LanguageCode='auto'){if(this.recognition&&this.promise){try{this.recognition.stop();}catch{}return this.promise.then(r=>{if(language!=='auto')r.language=language;return r;});}if(!this.recorder||!this.promise)return Promise.reject(new SpeechServiceError('Voice recording has not started.','recording-failed'));if(this.recorder.state!=='inactive')this.recorder.stop();return this.promise.then(r=>{if(language!=='auto')r.language=language;return r;});}
 cancel(){try{this.recognition?.abort();}catch{}if(this.recorder&&this.recorder.state!=='inactive')this.recorder.stop();this.stream?.getTracks().forEach(t=>t.stop());this.recognition=null;this.recorder=null;this.stream=null;this.promise=null;this.done=true;}}
