import { useEffect, useState } from 'react';
import { Check, CheckCircle2, Clock3, X, XCircle } from 'lucide-react';
import { useApp } from '../AppContext';
import { Card } from './ui/Card';
import { Button } from './ui/Button';
import { loadMarket, respondToBuyerRequest } from '../services/marketService';
import type { BuyerRequest } from '../types';
type LinkedRequest=BuyerRequest&{buyerName?:string;buyerMobile?:string;buyerEmail?:string;buyerDistrict?:string;buyerState?:string;variety?:string;message?:string;respondedAt?:string};
export function FarmerConnectionsScreen(){const{profile}=useApp();const[requests,setRequests]=useState<LinkedRequest[]>([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState<string|null>(null);const refresh=async()=>{if(!profile)return;try{const data=await loadMarket('farmer',profile.id);setRequests(data.requests as LinkedRequest[]);}finally{setLoading(false);}};useEffect(()=>{void refresh();if(!profile)return;const timer=window.setInterval(()=>void refresh(),2500);return()=>window.clearInterval(timer);},[profile?.id]);const respond=async(r:LinkedRequest,status:'accepted'|'rejected')=>{if(!profile)return;setBusy(r.id);try{await respondToBuyerRequest(r.id,profile.id,'farmer',status);await refresh();}finally{setBusy(null);}};if(!profile)return null;return <div className="px-4 pt-4 pb-2 sm:px-0"><div className="mb-4"><p className="text-xs font-bold uppercase tracking-wide text-brand-deep">KisanLink</p><h1 className="text-xl font-extrabold text-ink">Farmer–Buyer Connections</h1><p className="mt-1 text-sm text-ink-soft">Every request is stored in SQLite and synchronized between both dashboards.</p></div>{loading?<Card>Loading connections…</Card>:requests.length===0?<Card><p className="font-bold text-ink">No connections yet.</p><p className="mt-1 text-sm text-ink-soft">A buyer request or your request to a buyer will appear here.</p></Card>:<div className="space-y-3">{requests.map(r=><Card key={r.id}><div className="flex items-start justify-between gap-3"><div><p className="font-extrabold text-ink">{r.buyerName||'Buyer'}</p><p className="mt-1 text-sm text-ink-soft">{r.cropName} · {r.requestedQuantity} qtl · Grade {r.grade}</p><p className="mt-1 text-xs text-ink-faint">{r.buyerDistrict||''}{r.buyerState?`, ${r.buyerState}`:''}</p></div><Status status={r.status}/></div>{r.message&&<p className="mt-3 rounded-xl bg-surface-alt p-3 text-sm text-ink-soft">{r.message}</p>}{r.status==='pending'&&<div className="mt-4 flex gap-2"><Button size="sm" onClick={()=>respond(r,'accepted')} disabled={busy===r.id}><Check size={15}/> Accept</Button><Button size="sm" variant="outline" onClick={()=>respond(r,'rejected')} disabled={busy===r.id}><X size={15}/> Reject</Button></div>}{r.status==='accepted'&&<div className="mt-3 grid grid-cols-1 gap-2 rounded-xl bg-brand-soft p-3 text-sm sm:grid-cols-2"><div><p className="text-xs text-ink-soft">Buyer business</p><p className="font-bold text-ink">{r.buyerName}</p></div><div><p className="text-xs text-ink-soft">Mobile</p><p className="font-bold text-ink">{r.buyerMobile||'Not available'}</p></div>{r.buyerEmail&&<div><p className="text-xs text-ink-soft">Email</p><p className="font-bold text-ink">{r.buyerEmail}</p></div>}<div><p className="text-xs text-ink-soft">Status</p><p className="font-bold text-brand-deep">Accepted</p></div></div>}</Card>)}</div>}</div>}
function Status({status}:{status:BuyerRequest['status']}){if(status==='accepted')return <span className="flex items-center gap-1 rounded-full bg-brand-soft px-2 py-1 text-xs font-bold text-brand-deep"><CheckCircle2 size={14}/> Accepted</span>;if(status==='rejected')return <span className="flex items-center gap-1 rounded-full bg-red-50 px-2 py-1 text-xs font-bold text-red-600"><XCircle size={14}/> Rejected</span>;return <span className="flex items-center gap-1 rounded-full bg-caution/10 px-2 py-1 text-xs font-bold text-caution"><Clock3 size={14}/> Pending</span>;}
